all:
  project_dir: "/mnt/isilon/microbiome/analysis/danielsg/PCMP_ITS_pipeline/test"
  mux_dir: "multiplexed_fastq" #directory that holds multiplexed data or leave blank if files already demultiplexed
  demux_dir:  #leave blank to demultiplex or full path to demultiplexed gunzipped fastq files
  mapping_file: "test_mapping_file.tsv" #relative to project_dir
  forward_direction: TRUE #If TRUE, use the forward reads; else, use reverse

demux:
    mismatch: 0
    revcomp: TRUE

trim:
  f_primer: CTTGGTCATTTAGAGGAAGTAA
  r_primer: GCTGCGTTCTTCATCGATGC
  mismatch: 2
  min_length: 15
  align_id: 0.85

otu:
  expected_error: 1
  otu_id: 0.99
  chimera_db: #leave blank if using mockdna positive controls

blastn:
  ncbi_db: "/mnt/isilon/microbiome/analysis/biodata/blast/nt_20240612/nt"

brocc:
  taxonomy_db: "/mnt/isilon/microbiome/analysis/biodata/brocc_nt_database/taxonomy.db"
